

CFGmakeRun:=Makefile.run.go01
CFGmakeRun:=Makefile.run.go02
CFGmakeRun:=Makefile.run.document01

GoTOP:=CMSS200A_SDK_TPC__2018_0108
wputPATH:=ftp://coe:coe@192.168.1.93/

# https://github.com/antoine-richard/gomobile-text.git
# git clone https://github.com/96boards-bubblegum/linaro-adfu-tool.git

ifdef XXXX1111
gl : 
	find CMSS200A_SDK_TPC \
		-type f \
		-name "*.c" \
		-o -name "*.h" \
		-o -name "*.bat" \
		-o -name "*.BAT" \
		> 1.txt
	find CMSS200A_SDK_TPC \
		-type f \
		-name "*.txt" \
		-o -name "*.lst" \
		-o -name "*.A51" \
		|grep -v CMSS200A_SDK_TPC/history.txt \
		|grep -v CMSS200A_SDK_TPC/1.txt \
		> 2.txt
	for aa1 in `cat 1.txt 2.txt`  ;\
		do \
		dos2unix $${aa1}                                      || exit 33 ; \
		cat $${aa1} |   iconv -c -f cp936 -t utf8 > 3.txt        || exit 34 ; \
		cat 3.txt > $${aa1}                                   || exit 35 ; \
		done
endif

ftpCMA200u:=ftp://ddcma200:dd@192.168.1.93
ftpCMA200d:=ftp://ddcma200:dd@192.168.1.93

up1:=upload_build_script01
$(up1):=src3/201__buildallprj.bat  case/fwpkg/buildallprj.bat  
up1:
	$(wputX1)     $(firstword $($(up1)))    $(ftpCMA200u)/$(word 2,$($(up1)))
	@md5sum       $(firstword $($(up1)))    


up2:=upload_build_script02
$(up2):=src3/203__buildfw_snor.bat   case/fwpkg/buildfw_snor.bat
up2:
	$(wputX1)     $(firstword $($(up2)))    $(ftpCMA200u)/$(word 2,$($(up2)))
	@md5sum       $(firstword $($(up2)))    

dl1:=download_log_01
$(dl1):=case/fwpkg/buildlist.log    src3/207__buildlist.log
dl1:
	$(wgetY1)     $(ftpCMA200u)/$(firstword $($(dl1)))    > $(word 2,$($(dl1)))
	@md5sum                                                 $(word 2,$($(dl1)))
	cat $(word 2,$($(dl1))) | iconv -f cp936 -t utf8      > $(word 2,$($(dl1))).txt

dl2:=download_log_02
$(dl2):=case/fwpkg/buildlist2.log    src3/208__buildlist2.log
dl2:
	$(wgetY1)     $(ftpCMA200u)/$(firstword $($(dl2)))    > $(word 2,$($(dl2)))
	@md5sum                                                 $(word 2,$($(dl2)))
	cat $(word 2,$($(dl2))) | iconv -f cp936 -t utf8      > $(word 2,$($(dl2))).txt

dl3:=download_log_03
$(dl3):=case/fwpkg/CMSS200A.fw    src3/301__CMSS200A.fw
dl3:
	$(wgetY1)     $(ftpCMA200u)/$(firstword $($(dl3)))    > $(word 2,$($(dl3)))
	@md5sum                                                 $(word 2,$($(dl3)))
	@echo $$(ls -l $(word 2,$($(dl3)))) $$(ls -lh $(word 2,$($(dl3)))|awk '{print $$5}')

dl4:=download_log_04
$(dl4):=case/fwpkg/fwImageFile.bin    src3/302__fwImageFile.bin
dl4:
	$(wgetY1)     $(ftpCMA200u)/$(firstword $($(dl4)))    > $(word 2,$($(dl4)))
	@md5sum                                                 $(word 2,$($(dl4)))
	@echo $$(ls -l $(word 2,$($(dl4)))) $$(ls -lh $(word 2,$($(dl4)))|awk '{print $$5}')

showRunHelpList += up1 up2 dl1 dl2 dl3 dl4 


