/* generated by ResBuilder, (c)2003 Actions */
/******************************************/
#ifndef _LANG_ID
#define _LANG_ID
//language id
#define LAN_ID_SCHINESE         0           //中文简体
#define LAN_ID_ENGLISH          1           //英文
#define LAN_ID_TCHINESE         2           //中文繁体
#define LAN_ID_JAPANESE         3           //日文
#define LAN_ID_KOREAN           4           //韩文
#define LAN_ID_FRENCH           5           //法语
#define LAN_ID_GERMANY          6           //德国语
#define LAN_ID_ITALIAN          7           //意大利语
#define LAN_ID_DUTCH            8           //荷兰语
#define LAN_ID_PORTUGUESE       9           //葡萄牙语
#define LAN_ID_SPANISH          10          //西班牙语
#define LAN_ID_SWEDISH          11          //瑞典语
#define LAN_ID_CZECHISH         12          //捷克语
#define LAN_ID_DENISH           13          //丹麦语
#define LAN_ID_POLAND           14          //波兰语
#define LAN_ID_RUSSIAN          15          //俄罗斯语
#define LAN_ID_TURKISH          16          //土耳其语
#define LAN_ID_HEBREW           17          //西伯莱文
#define LAN_ID_THAI             18          //泰国语
#define LAN_ID_HUNGARIAN        19          //匈牙利语
#define LAN_ID_ROMANIAN         20          //罗马尼亚
#define LAN_ID_RABBINIC         21          //阿拉伯
#define LAN_ID_INDONESIAN       22          //印尼
#define LAN_ID_GREEK            23          //希腊文
#define LAN_ID_SLOVAKIAN        24          //斯洛伐克语
#define LAN_ID_FINNISH          25          //芬兰语
#define LAN_ID_CROATIA          26          //
#define LANGUAGETOTAL           24
#endif